### ISSUE TITLE
Attending the workshop with a Linux machine

### ISSUE THREAD

**Issue by mcnoat** [Remi-Gau/matlab_clean_code_workshop#1]
Hello,
I only have Linux installed on my laptop. I have been thinking about switching to a dual boot setup for quite a while, so if necessary, I could try to get that set up by Friday.
That being said, the first line after the title of the description of the workshop (https://remi-gau.github.io/matlab_clean_code_workshop/) mentioned GNU Octave, but it isn't mentioned as one of the options under "Requirements". Hence, I'm a bit confused: Is having Octave on my machine sufficient or should I come with an installation of MATLAB?

**Comment by Remi-Gau** [comment]
You should be fine using just Linux + Octave for most things.

It will actually even be easier for certain things: testing things with continuous integration on gitlab and matlab is more complicated than with Octave.

**Comment by Remi-Gau** [comment]
If it helps see #4
